### PR TITLE
Fix/add now without highlight

### LINKED ISSUE #182: .future class is on current date
The `.future` class is shown on the current date.  If you use `highlight:now` then the `.future` class is no longer on the current date.  It seems that the `.now` class should be on the current date at all times.  Then only add the `stroke: red` style when `.now` is used with `.highlight`.

### PR DESCRIPTION
**Pull request by snumb130**
When trying to target `.future` class in CSS I noticed that the `.future` class is added to the current date.  The only way to get the `.now` class was use the `highlight` option.  It seemed more appropriate to have the `.now` class to always be present on the current date.  This pull request is for that.  

It adds a class of `highlight-now` because the current date highlighting is supposed to be different and since the `.now` class is always there it couldn't be styled like it was.  

I also changed the way that future is determined.  Since this fix requires checking to see if it is the current date to add the `.now` class, it now bases the addition of `.future` on whether or not the date has failed `pastDate` and `currentDate`

Fixes #182

### CODE REVIEW

**Comment by snumb130** [comment]
I squashed this down to one commit.

**Comment by wa0x6e** [comment]
Couldn't you achieve the highlight result on the current date with `.highlight.now` instead of `.highlight-now` ?

**Comment by snumb130** [comment]
Yes. I originally had it that way, but when I ran your tests the linter
threw and error about adjoining classes.

https://github.com/CSSLint/csslint/wiki/Disallow-adjoining-classes


On Fri, Mar 18, 2016, 5:06 AM Wan Qi Chen <notifications@github.com> wrote:

> Couldn't you achieve the highlight result on the current date with
> .highlight.now instead of .highlight-now ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/wa0x6e/cal-heatmap/pull/183#issuecomment-198288922>
>
-- 

Luke Howell

File: src/cal-heatmap.js [hunk 1]
```diff
@@ -1868,7 +1871,7 @@ CalHeatMap.prototype = {
 		if (this.options.highlight.length > 0) {
 			for (var i in this.options.highlight) {
 				if (this.options.highlight[i] instanceof Date && this.dateIsEqual(this.options.highlight[i], d)) {
-					return " highlight" + (this.isNow(this.options.highlight[i]) ? " now": "");
+          return this.isNow(this.options.highlight[i]) ? " highlight-now": " highlight";
```
Comment (wa0x6e) [inline src/cal-heatmap.js]: I think you should always add the `highlight` class, since some people will not want to highlight the current time differently

File: src/cal-heatmap.js [hunk 2]
```diff
@@ -2915,8 +2926,10 @@ CalHeatMap.prototype = {
 			".graph-rect": {},
 			"rect.highlight": {},
 			"rect.now": {},
+			"rect.highlight-now": {},
 			"text.highlight": {},
 			"text.now": {},
+			"text.highlight-now": {},
```
Comment (wa0x6e) [inline src/cal-heatmap.js]: `rect.now` and `text.now` are now useless, and can be removed

File: src/cal-heatmap.js [hunk 3]
```diff
@@ -1868,7 +1871,7 @@ CalHeatMap.prototype = {
 		if (this.options.highlight.length > 0) {
 			for (var i in this.options.highlight) {
 				if (this.options.highlight[i] instanceof Date && this.dateIsEqual(this.options.highlight[i], d)) {
```
Comment (wa0x6e) [inline src/cal-heatmap.js]: You can remove the type check, since you added one in the `dateIsEqual` function

File: test/src/misc/getHighlightClassName.js [hunk 4]
```diff
@@ -14,13 +14,6 @@ test("Return the highlight classname if a date should be highlighted", function(
 	strictEqual(cal.getHighlightClassName(new Date(2000, 0, 1)), " highlight");
 });
 
-test("Return the highlight and now classname if a date should be highlighted and is now", function() {
-	expect(1);
-
-	var cal = createCalendar({highlight: [new Date(2000, 0, 1), new Date()]});
-	strictEqual(cal.getHighlightClassName(new Date()), " highlight now");
```
Comment (wa0x6e) [inline test/src/misc/getHighlightClassName.js]: Replacing `highlight now` by `highlight highlight-now` should make the test pass

**Comment by wa0x6e** [comment]
Can you also make sure to use TAB, and not space for indentation ?

File: src/cal-heatmap.js (hunk 1 above)
Comment (snumb130) [inline src/cal-heatmap.js]: Since the default CSS has both, the user will still have to override the `highlight-now` class to remove the styles.  So either way they will have to include it unless they are using the default styling for it.  Correct me if I am wrong on this.  So for example, the default is 

```css
.cal-heatmap-container rect.highlight
{
	stroke:#444;
	stroke-width:1
}
```

The `highlight-now` is added with the following default

```css
.cal-heatmap-container rect.highlight-now
{
	stroke: red
}
```

Therefore if the user wants to use the `highlight` only they are still going to have to override the styling of `highlight-now`.  The only real way to save anything here is to use adjoining classes (`highlight.now`) which the linter does not allow.  Am I thinking correctly here?

File: src/cal-heatmap.js (hunk 3 above)
Comment (snumb130) [inline src/cal-heatmap.js]: Done.

File: test/src/misc/getHighlightClassName.js (hunk 4 above)
Comment (snumb130) [inline test/src/misc/getHighlightClassName.js]: I added a new test, but just checking for `hightlight-now` alone until response on whether or not it makes sense to use both `highlight` and `highlight-now`

**Comment by connorshea** [comment]
Any updates on this?

**Comment by snumb130** [comment]
@wa0x6e Let me know when you have evaluated this comment and I will either leave or fix and push changes.  https://github.com/wa0x6e/cal-heatmap/pull/183#discussion_r56769090

**Comment by snumb130** [comment]
@wa0x6e Do you have an answer/opinion on this? https://github.com/wa0x6e/cal-heatmap/pull/183#discussion_r56769090

**Comment by wa0x6e** [comment]
I'll take a look asap

**Comment by snumb130** [comment]
Just checking back in to make sure this hasn't fell through the cracks.  Just curious if https://github.com/wa0x6e/cal-heatmap/pull/183#discussion_r56769090 makes sense in response to https://github.com/wa0x6e/cal-heatmap/pull/183#discussion_r56762161

**Comment by wa0x6e** [comment]
Thank you for the wait
